/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamApprovalsRouteImport } from './routes/team-approvals'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MyGoalsRouteImport } from './routes/my-goals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const TeamApprovalsRoute = TeamApprovalsRouteImport.update({
  id: '/team-approvals',
  path: '/team-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGoalsRoute = MyGoalsRouteImport.update({
  id: '/my-goals',
  path: '/my-goals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-goals': typeof MyGoalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team-approvals': typeof TeamApprovalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-goals': typeof MyGoalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team-approvals': typeof TeamApprovalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-goals': typeof MyGoalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team-approvals': typeof TeamApprovalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/my-goals'
    | '/reset-password'
    | '/team-approvals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/my-goals' | '/reset-password' | '/team-approvals'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/my-goals'
    | '/reset-password'
    | '/team-approvals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyGoalsRoute: typeof MyGoalsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeamApprovalsRoute: typeof TeamApprovalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-approvals': {
      id: '/team-approvals'
      path: '/team-approvals'
      fullPath: '/team-approvals'
      preLoaderRoute: typeof TeamApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-goals': {
      id: '/my-goals'
      path: '/my-goals'
      fullPath: '/my-goals'
      preLoaderRoute: typeof MyGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyGoalsRoute: MyGoalsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeamApprovalsRoute: TeamApprovalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
